services:
  homer:
    container_name: homer
    image: b4bz/homer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - homer_assets:/www/assets
      - /volume1/docker/home_servers/synology/services/homer/config.yml:/www/config/config.yml:ro

volumes:
  homer_assets:
