services:
  kavita:
    container_name: kavita
    image: kizaing/kavita:latest
    restart: unless-stopped
    ports:
      - "5002:5000"
    volumes:
      - kavita_config:/kavita/config
      - /volume1/books:/books:ro
    environment:
      - TZ=Europe/Rome

volumes:
  kavita_config:
